-- CURRENT DATE/TIME
SELECT CURDATE();
SELECT CURTIME();
SELECT NOW();

-- EXTRACTION
SELECT YEAR(CURDATE());
SELECT MONTH(CURDATE());
SELECT DATE(CURDATE());

SELECT MONTHNAME(CURDATE());
SELECT DAYNAME(CURDATE());

SELECT HOUR(NOW());     -- or HOUR(CURTIME())
SELECT MINUTE(NOW());   -- or MINUTE(CURTIME())
SELECT SECOND(NOW());   -- or SECOND(CURTIME())


-- CALCULATION
SELECT DATEDIFF(DAY_FIRST, DAY_LAST) AS total_days;


-- FORMATTING
UPDATE users
SET dates = DATE_FORMAT(dates, '%Y-%m-%d');